Identify 'lv_' variables as vertical coordinates.
ncl_convert2nc starts its vertical coordinate variables with the
string "lv_". Added this to the set of regular expressions to match
in metpy.xarray.coordinate_criteria.

For example, when NARR grib files are converted from grib to netCDF
the 10-m zonal wind is stored in a variable called U_GRD_221_HTGL
with a vertical coordinate lv_HTGL5.
    long_name:    fixed height above ground
    units:        m

Let metpy.parse_cf() recognize this.

Otherwise you get an Attribute error
AttributeError: vertical attribute is not available.